# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define "web" do |web|
    web.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "4096"
    end

    web.vm.box = "crzyjcky/linuxmint171"
    web.vm.network "private_network", ip: "192.168.33.70"
    web.vm.network "forwarded_port", guest: 8080, host: 28080
    web.vm.provision "shell", path: "provision-web.sh"
  end

  config.vm.network "forwarded_port", guest: 22, host: 1234
end
